### ISSUE TITLE
Error in safe tick TypeError: Cannot read properties of undefined 

### ISSUE THREAD

**Issue by ghost** [bytesbay/chain-syncer#1]
Little bit modified your example for readme:

```
const { ChainSyncer, InMemoryAdapter } = require('chain-syncer');
const ethers = require('ethers');
const ERC20ABI = require('./ERC20ABI.json');

const default_adapter_which_you_need_to_change_to_any_other = new InMemoryAdapter();

// const ethersjs_provider = new ethers.providers.JsonRpcProvider('https://data-seed-prebsc-1-s1.binance.org:8545'); // BSC testnet rpc
const ethersjs_provider = new ethers.providers.JsonRpcProvider('https://bsc-dataseed.binance.org/'); // BSC prod rpc

const contracts = {
    'BUSD': {
        abi: ERC20ABI,
        network: {
            address: '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56',
            deployed_transaction: '0x0f01fc521030f178115c880e200b09a40c9510f49de227aa880276f92670a3d6'
        }
    }
}

const syncer = new ChainSyncer(default_adapter_which_you_need_to_change_to_any_other, {
    tick_interval: 3000,
    query_block_limit: 1000,
    verbose: true,
    block_time: 3500,
    ethers_provider: ethersjs_provider,
    async contractsGetter(contract_name) {
        const contract = contracts[contract_name];
        return {
            inst: new ethers.Contract(contract.network.address, contract.abi, ethersjs_provider),
            deployed_transaction_hash: contract.network.deployed_transaction,
        };
    },
});

syncer.start();

syncer.on('BUSD.Transfer#default-stream', async (
    from,
    to,
    token_id,
    { global_index, from_address, block_number, block_timestamp, transaction_hash }
) => {
    console.log(`${block_number} ${transaction_hash}`)
}); 
```

OUTPUT:

```
$ node index.js
[MAXBLOCK: 18309565] Defualt tick ...  7 events added
124241 0x0f01fc521030f178115c880e200b09a40c9510f49de227aa880276f92670a3d6
124446 0xacce20b2c723babf6a6fa760bf3b0cd980532b8d8c0c38388e52b08d13466d9f
125086 0x02c23aabff5fcbf043992a50a2618e1c9182b02118b96378966746081d0c1dd1
getTransaction error in 0x76c32a63ced1fdf09f2a8dd03495b3bf94d37951a46c22e7284d1ac916a1528c tx
getTransaction error in 0x53753bef87dc1f8ca76de33de41ade5047e485694bed9076b48045e42dd25176 tx
Event has no tx, trying to fetch again (problem with RPC)
Error in safe tick TypeError: Cannot read properties of undefined (reading 'from')
    at O.v (/home/piron/Desktop/chain-syncer-app/node_modules/chain-syncer/dist/chain-syncer.umd.min.js:3:7906)
    at /home/piron/Desktop/chain-syncer-app/node_modules/chain-syncer/dist/chain-syncer.umd.min.js:3:9333
    at Array.map (<anonymous>)
    at /home/piron/Desktop/chain-syncer-app/node_modules/chain-syncer/dist/chain-syncer.umd.min.js:3:9307
    at Array.map (<anonymous>)
    at O.<anonymous> (/home/piron/Desktop/chain-syncer-app/node_modules/chain-syncer/dist/chain-syncer.umd.min.js:3:9274)
    at d (/home/piron/Desktop/chain-syncer-app/node_modules/chain-syncer/dist/chain-syncer.umd.min.js:3:1230)
    at Generator._invoke (/home/piron/Desktop/chain-syncer-app/node_modules/chain-syncer/dist/chain-syncer.umd.min.js:3:983)
    at Generator.next (/home/piron/Desktop/chain-syncer-app/node_modules/chain-syncer/dist/chain-syncer.umd.min.js:3:1593)
    at u (/home/piron/Desktop/chain-syncer-app/node_modules/chain-syncer/dist/chain-syncer.umd.min.js:3:6468)
```

**Comment by bytesbay** [comment]
That errors does not break the scanner, just wait until RPC won't return errors

**Comment by bytesbay** [comment]
default BSC RPCs are quite strange
